"""removed quantity from oders table

Revision ID: 24c06ca79a3a
Revises: 125a0e68f041
Create Date: 2025-10-30 20:57:28.282196

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24c06ca79a3a"
down_revision: Union[str, Sequence[str], None] = "125a0e68f041"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "quantity")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("quantity", sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###
