"""fixed config_table

Revision ID: 41013efc885e
Revises: bd289561e9c1
Create Date: 2025-11-20 17:33:22.229194

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "41013efc885e"
down_revision: Union[str, Sequence[str], None] = "bd289561e9c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "config_table",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
    )
    op.add_column(
        "config_table", sa.Column("updated_at", sa.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "config_table", sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("config_table", "deleted_at")
    op.drop_column("config_table", "updated_at")
    op.drop_column("config_table", "created_at")
    # ### end Alembic commands ###
